//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetDataPublishes", ReplyAction="http://tempuri.org/IDataService/GetDataPublishesResponse")]
        BusinessLayer.Models.MDataPublish[] GetDataPublishes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetDataPublishes", ReplyAction="http://tempuri.org/IDataService/GetDataPublishesResponse")]
        System.Threading.Tasks.Task<BusinessLayer.Models.MDataPublish[]> GetDataPublishesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/InsertSensorData", ReplyAction="http://tempuri.org/IDataService/InsertSensorDataResponse")]
        bool InsertSensorData(BusinessLayer.Models.MDataPublish dataPublish);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/InsertSensorData", ReplyAction="http://tempuri.org/IDataService/InsertSensorDataResponse")]
        System.Threading.Tasks.Task<bool> InsertSensorDataAsync(BusinessLayer.Models.MDataPublish dataPublish);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : PresentationLayer.ServiceReference1.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<PresentationLayer.ServiceReference1.IDataService>, PresentationLayer.ServiceReference1.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BusinessLayer.Models.MDataPublish[] GetDataPublishes() {
            return base.Channel.GetDataPublishes();
        }
        
        public System.Threading.Tasks.Task<BusinessLayer.Models.MDataPublish[]> GetDataPublishesAsync() {
            return base.Channel.GetDataPublishesAsync();
        }
        
        public bool InsertSensorData(BusinessLayer.Models.MDataPublish dataPublish) {
            return base.Channel.InsertSensorData(dataPublish);
        }
        
        public System.Threading.Tasks.Task<bool> InsertSensorDataAsync(BusinessLayer.Models.MDataPublish dataPublish) {
            return base.Channel.InsertSensorDataAsync(dataPublish);
        }
    }
}
