//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataPublish
    {
        public int DataPublishId { get; set; }
        public Nullable<int> SensorId { get; set; }
        public Nullable<int> DataId { get; set; }
        public string DataValue { get; set; }
        public Nullable<System.DateTime> PublishTime { get; set; }
    
        public virtual DataType DataType { get; set; }
        public virtual Sensor Sensor { get; set; }
    }
}
